typography_spectrum: 0.83433766348863
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8108942272103168
  lightness: 0.7713734697154689
  saturation: 0.8499512063910931
  rhythmicContrast: 0.6124342282899568
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6079828688088059
analytics:
  google: null
  facebook: null
  twitter: null
name: DeuceWorldOrder
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Store
    url: 'http://www.deuceunlimited.com'
    type: external
favicon: null
title: Deuce World Order
purpose: []
